title: Sandeep Nanda
subtitle: ">>>YATB (Yet Another Tech Blog)"
author: Sandeep Nanda
email: contact@sandeepnanda.com
description: This is where I keep notes of my encounters with the world, professional and personal
static_url: /assets/
domain: http://sandeepnanda.com

sass:
    sass_dir: assets/_sass

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "post" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      comments: true
      sharing: true
  -
    scope:
      path: "technology"
      type: "post" # previously `post` in Jekyll 2.2.
    values:
      categories: "technology"
  -
    scope:
      path: "quotes"
      type: "post" # previously `post` in Jekyll 2.2.
    values:
      categories: "quotes"
  -
    scope:
      path: "travel"
      type: "post" # previously `post` in Jekyll 2.2.
    values:
      categories: "travel"

enable_sharing: true
lsi: false
highlighter: pygments
paginate: 10
markdown: redcarpet
redcarpet:
  extensions:
    - smart
permalink: /blog/:title/
exclude: ["CNAME", "README.md", "Rakefile", "generate.rb", "Gemfile", "Gemfile.lock"]
gems:
  - jekyll-sitemap
excerpt_separator: '<!--more-->'
recent_posts: 8

# Github repositories
github_user: snanda85
github_repo_count: 5
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: sunny_nanda
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: snanda85
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-54329779-1

# Facebook Like
facebook_like: true

#stackoverflow_user: 956362
infolinks_pid: 2189848
